# Generated by Django 6.0.6 on 2026-07-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('accountant', 'Accountant'), ('billing_mgr', 'Billing Manager')], default='cashier', max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billing Staff',
                'verbose_name_plural': 'Billing Staff',
                'ordering': ['name'],
            },
        ),
    ]
