# Generated by Django 6.0.6 on 2026-06-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('head_chef', 'Head Chef'), ('chef', 'Chef'), ('sous_chef', 'Sous Chef'), ('line_cook', 'Line Cook'), ('kitchen_mgr', 'Kitchen Manager')], default='chef', max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kitchen Staff',
                'verbose_name_plural': 'Kitchen Staff',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='kitchenticket',
            options={'ordering': ['-priority', 'received_at']},
        ),
        migrations.AlterModelOptions(
            name='kitchenticketitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='customer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='kitchen_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15),
        ),
    ]
