# Generated by Django 6.0.6 on 2026-07-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchenstaff_alter_kitchenticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticketitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
