# Generated by Django 6.0.6 on 2026-06-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('sub_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
