# Generated by Django 6.0.6 on 2026-07-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_bill_options_bill_paid_at_bill_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Discount', max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, default=0, help_text='% of the bill subtotal to discount automatically. Set to 0 for no default discount.', max_digits=5)),
                ('is_active', models.BooleanField(default=False, help_text='Only one discount setting can be active — activating this one deactivates the others.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Setting',
                'verbose_name_plural': 'Discount Settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VATSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard VAT', max_length=100)),
                ('percent', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Only one VAT setting can be active — activating this one deactivates the others.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VAT Setting',
                'verbose_name_plural': 'VAT Settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount (Rs.)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent off (0–100) or a flat Rs. amount off, depending on type above.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Leave blank to start immediately.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank to run with no end date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='menu.fooditem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
