# Generated by Django 6.0.6 on 2026-07-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_discountsetting_vatsetting_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='fa-circle-plus', help_text='Font Awesome icon class, e.g. fa-glass-water, fa-tissue.', max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Only charged when "is free" is unchecked.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quick Item',
                'verbose_name_plural': 'Quick Items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_free', models.BooleanField(default=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('served', 'Served')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='menu.quickitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_requests', to='menu.tablesession')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
