# Generated by Django 6.0.6 on 2026-07-19 07:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_orderitem_cancelled_at_orderitem_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to hide the calorie badge.', null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.CharField(blank=True, help_text='Comma-separated list, shown in the item detail modal. Leave blank to hide.', max_length=500),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_chef_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Shown as the veg/non-veg indicator on the menu. Defaults to False for existing dishes — review and set correctly per dish before relying on it.'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0.0–5.0. Leave blank to hide the rating badge.', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
    ]
