# Generated by Django 6.0.6 on 2026-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='pin',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
